name: duckoo Workflow

on: [pull_request]
      
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "16"
          - "18"
          - "20"

    steps:
      - uses: actions/checkout@v4
      
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx.
